name: Create Lichess game

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: create-game
  cancel-in-progress: true

jobs:
  create_game:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data folder exists
        run: mkdir -p data

      - name: Load secrets into environment
        run: |
          echo "LICHESS_HUMAN_TOKEN=${{ secrets.LICHESS_HUMAN_TOKEN }}" >> $GITHUB_ENV
          echo "LICHESS_BOT_TOKEN=${{ secrets.LICHESS_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "LICHESS_BOT_USERNAME=${{ secrets.LICHESS_BOT_USERNAME }}" >> $GITHUB_ENV

      - name: Create game on Lichess
        run: python 01_create_game.py

      - name: Reset game data (only if creation succeeded)
        if: success()
        run: |
          python - <<'PY'
          import json
          from datetime import datetime, timezone
          import chess

          starting_fen = chess.STARTING_FEN

          # coup_blanc.txt vide
          open("data/coup_blanc.txt", "w", encoding="utf-8").close()

          # position.fen = position initiale
          with open("data/position.fen", "w", encoding="utf-8") as f:
              f.write(starting_fen)

          # dernier_coup.json avec date + position initiale
          payload = {
              "dernier_coup": None,
              "fen": starting_fen,
              "horodatage": datetime.now(timezone.utc).isoformat()
          }
          with open("data/dernier_coup.json", "w", encoding="utf-8") as f:
              json.dump(payload, f, ensure_ascii=False, indent=2)

          # move_history.json vide
          with open("data/move_history.json", "w", encoding="utf-8") as f:
              json.dump([], f, ensure_ascii=False, indent=2)
          PY

      - name: Debug data directory
        run: |
          ls -la data || true
          echo "game_id:"; test -f data/game_id.txt && cat data/game_id.txt || echo "missing"
          echo "fen:"; test -f data/position.fen && head -n1 data/position.fen || echo "missing"
          echo "last:"; test -f data/dernier_coup.json && cat data/dernier_coup.json || echo "missing"
          echo "history:"; test -f data/move_history.json && cat data/move_history.json || echo "missing"

      - name: Commit & push game data
        if: success()
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin "$BRANCH"
          git pull --rebase origin "$BRANCH" || true
          git add -f data/game_id.txt data/position.fen data/dernier_coup.json data/coup_blanc.txt data/move_history.json || true
          git commit -m "Init game data with starting FEN" || echo "No changes"
          git push --force-with-lease origin HEAD:"$BRANCH"
