name: Main

on:
  workflow_dispatch:

jobs:
  process_comments_white:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process comments and select white move
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_VIDEO_ID: ${{ secrets.YOUTUBE_VIDEO_ID }}
          LICHESS_HUMAN_TOKEN: ${{ secrets.LICHESS_HUMAN_TOKEN }}
        run: |
          python 03_process_comments.py
        continue-on-error: true  # ⬅ N'interrompt pas le workflow si aucun commentaire

      - name: Play white move
        run: |
          python 04_play_white.py
        continue-on-error: true  # ⬅ N'interrompt pas si le coup est vide
