name: Main

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: main-cycle
  cancel-in-progress: true

jobs:
  process_and_play:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo complet
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Install ImageMagick (nécessaire pour wand)
      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      # 4) Install dependencies Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5) Ensure data folder exists
      - name: Ensure data folder exists
        run: mkdir -p data

      # 6) Load secrets
      - name: Load secrets into environment
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> $GITHUB_ENV
          echo "YOUTUBE_VIDEO_ID=${{ secrets.YOUTUBE_VIDEO_ID }}" >> $GITHUB_ENV
          echo "LICHESS_HUMAN_TOKEN=${{ secrets.LICHESS_HUMAN_TOKEN }}" >> $GITHUB_ENV
          echo "LICHESS_BOT_TOKEN=${{ secrets.LICHESS_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "GH_WORKFLOW_TOKEN=${{ secrets.GH_WORKFLOW_TOKEN }}" >> $GITHUB_ENV

      # 7) Process comments → coup_blanc.txt
      - name: Process comments and select white move
        run: python 03_process_comments.py
        continue-on-error: true

      # 8) Commit coup_blanc.txt
      - name: Commit coup_blanc.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || true
          git add data/coup_blanc.txt || true
          git diff --cached --quiet || git commit -m "Update coup_blanc.txt [skip ci]"
          git push --force-with-lease origin main || true

      # 9) Play white move
      - name: Play white move
        run: python 04_play_white.py
        continue-on-error: true

      # 10) Delay to ensure Lichess sync after white move
      - name: Delay after white move
        run: sleep 3

      # 11) Play black move
      - name: Play black move
        run: python 05_play_black.py
        continue-on-error: true

      # 12) Delay to ensure Lichess sync after black move
      - name: Delay after black move
        run: sleep 5

      # 13) Commit updated game data
      - name: Commit updated game data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || true
          git add data/position.fen data/dernier_coup.json data/move_history.json || true
          git diff --cached --quiet || git commit -m "Update game state after moves [skip ci]"
          git push --force-with-lease origin main || true

      # 14) Generate black SVG + PNG
      - name: Generate black SVG & PNG
        run: python 06_generate_black_svg.py
        continue-on-error: true

      # 15) Commit SVG & PNG thumbnail
      - name: Commit SVG & PNG thumbnail
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || true
          git add data/thumbnail_black.svg data/thumbnail_black.png || true
          git diff --cached --quiet || git commit -m "Update black thumbnail [skip ci]"
          git push --force-with-lease origin main || true
