name: Main

on:
  workflow_dispatch:

permissions:
  contents: write  # Autorise les push vers le dépôt

jobs:
  process_and_play:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code du dépôt
      - uses: actions/checkout@v4

      # 2. Installer Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Récupérer et sélectionner le coup blanc
      - name: Process comments and select white move
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_VIDEO_ID: ${{ secrets.YOUTUBE_VIDEO_ID }}
          LICHESS_HUMAN_TOKEN: ${{ secrets.LICHESS_HUMAN_TOKEN }}
        run: |
          python 03_process_comments.py
        continue-on-error: true

      # 5. Commit et push coup_blanc.txt
      - name: Commit coup_blanc.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/coup_blanc.txt
          git commit -m "Update coup_blanc.txt [skip ci]" || echo "No changes to commit"
          git push

      # 6. Jouer le coup blanc
      - name: Play white move
        env:
          LICHESS_HUMAN_TOKEN: ${{ secrets.LICHESS_HUMAN_TOKEN }}
        run: |
          python 04_play_white.py
        continue-on-error: true

      # 7. Jouer le coup noir (Stockfish bot)
      - name: Play black move
        env:
          LICHESS_BOT_TOKEN: ${{ secrets.LICHESS_BOT_TOKEN }}
        run: |
          python 05_play_black.py
        continue-on-error: true

      # 8. Commit et push tous les fichiers mis à jour
      - name: Commit updated game data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/position.fen data/dernier_coup.json data/move_history.json || true
          git commit -m "Update game state after moves [skip ci]" || echo "No changes to commit"
          git push
