name: Main

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: main-cycle
  cancel-in-progress: true

jobs:
  process_and_play:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo complet
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Install ImageMagick + SVG support (rapide, sans man-db)
      - name: Install ImageMagick + SVG support
        run: |
          sudo apt-get update -qq
          sudo apt-get remove -y --purge man-db || true
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends imagemagick librsvg2-bin

      # 4) Cache pip
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 5) Install dependencies Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6) Ensure data folder exists
      - name: Ensure data folder exists
        run: mkdir -p data

      # 7) Load secrets
      - name: Load secrets into environment
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> $GITHUB_ENV
          echo "YOUTUBE_VIDEO_ID=${{ secrets.YOUTUBE_VIDEO_ID }}" >> $GITHUB_ENV
          echo "LICHESS_HUMAN_TOKEN=${{ secrets.LICHESS_HUMAN_TOKEN }}" >> $GITHUB_ENV
          echo "LICHESS_BOT_TOKEN=${{ secrets.LICHESS_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "GH_WORKFLOW_TOKEN=${{ secrets.GH_WORKFLOW_TOKEN }}" >> $GITHUB_ENV

      # 8) Process comments → coup_blanc.txt
      - name: Process comments and select white move
        run: python 03_process_comments.py
        continue-on-error: true

      # 9) Commit coup_blanc.txt
      - name: Commit coup_blanc.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || true
          git add data/coup_blanc.txt || true
          git diff --cached --quiet || git commit -m "Update coup_blanc.txt [skip ci]"
          git push --force-with-lease origin main || true

      # 10) Play white move
      - name: Play white move
        run: python 04_play_white.py
        continue-on-error: true

      # 11) Delay after white move
      - name: Delay after white move
        run: sleep 1

      # 12) Play black move
      - name: Play black move
        run: python 05_play_black.py
        continue-on-error: true

      # 13) Delay after black move
      - name: Delay after black move
        run: sleep 1

      # 14) Commit updated game data
      - name: Commit updated game data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || true
          git add data/position.fen data/dernier_coup.json data/move_history.json || true
          git diff --cached --quiet || git commit -m "Update game state after moves [skip ci]"
          git push --force-with-lease origin main || true

      # 15) Generate black SVG + PNG
      - name: Generate black SVG & PNG
        run: python 06_generate_black_svg.py
        continue-on-error: true

      # 16) Commit SVG & PNG thumbnail
      - name: Commit SVG & PNG thumbnail
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main || true
          git add data/thumbnail_black.svg data/thumbnail_black.png || true
          git diff --cached --quiet || git commit -m "Update black thumbnail [skip ci]"
          git push --force-with-lease origin main || true
