name: Main

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process_comments_white:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process comments and select white move
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_VIDEO_ID: ${{ secrets.YOUTUBE_VIDEO_ID }}
          LICHESS_HUMAN_TOKEN: ${{ secrets.LICHESS_HUMAN_TOKEN }}
        run: |
          python 03_process_comments.py
        continue-on-error: true  # ⬅ empêche l'échec du job si aucun commentaire

      - name: Play white move
        run: |
          python 04_play_white.py
        continue-on-error: true  # ⬅ idem, si le coup est vide ça ne bloque pas

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/coup_blanc.txt
          git commit -m "♟️ Coup blanc joué" || echo "Rien à committer"
          git push
